// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using college_management.Dados.Contexto;

#nullable disable

namespace college_management.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    [Migration("20250421170624_FixMerge")]
    partial class FixMerge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("college_management.Dados.Modelos.Avaliacao", b =>
                {
                    b.Property<uint>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId1")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("P1")
                        .HasMaxLength(10)
                        .HasColumnType("REAL");

                    b.Property<float?>("P2")
                        .HasMaxLength(10)
                        .HasColumnType("REAL");

                    b.Property<float?>("P3")
                        .HasMaxLength(10)
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("MateriaId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("GestorId");

                    b.HasIndex("GestorId1");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.CorpoDocente", b =>
                {
                    b.Property<uint>("DocenteId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("DocenteId", "MateriaId");

                    b.HasIndex("GestorId");

                    b.HasIndex("GestorId1");

                    b.HasIndex("MateriaId");

                    b.ToTable("CorpoDocente");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.GradeCurricular", b =>
                {
                    b.Property<uint>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("CursoId", "MateriaId");

                    b.HasIndex("GestorId");

                    b.HasIndex("GestorId1");

                    b.HasIndex("MateriaId");

                    b.ToTable("GradeCurricular");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Matricula", b =>
                {
                    b.Property<uint?>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Modalidade")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Periodo")
                        .HasColumnType("INTEGER");

                    b.HasKey("CursoId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("GestorId");

                    b.HasIndex("GestorId1");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Modelo", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GestorId");

                    b.HasIndex("GestorId1");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("college_management.Dados.Modelos.TurmaAluno", b =>
                {
                    b.Property<uint>("TurmaId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("GestorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TurmaId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("GestorId");

                    b.ToTable("TurmaAluno");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Curso", b =>
                {
                    b.HasBaseType("college_management.Dados.Modelos.Modelo");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Materia", b =>
                {
                    b.HasBaseType("college_management.Dados.Modelos.Modelo");

                    b.Property<uint>("CargaHoraria")
                        .HasColumnType("INTEGER");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Turma", b =>
                {
                    b.HasBaseType("college_management.Dados.Modelos.Modelo");

                    b.Property<uint?>("DocenteId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("DocenteId1")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("MateriaId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turno")
                        .HasColumnType("INTEGER");

                    b.HasIndex("DocenteId");

                    b.HasIndex("DocenteId1");

                    b.HasIndex("MateriaId");

                    b.HasIndex("MateriaId1");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Usuario", b =>
                {
                    b.HasBaseType("college_management.Dados.Modelos.Modelo");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Aluno", b =>
                {
                    b.HasBaseType("college_management.Dados.Modelos.Usuario");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Docente", b =>
                {
                    b.HasBaseType("college_management.Dados.Modelos.Usuario");

                    b.ToTable("Docente");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Gestor", b =>
                {
                    b.HasBaseType("college_management.Dados.Modelos.Usuario");

                    b.Property<int>("Cargo")
                        .HasColumnType("INTEGER");

                    b.ToTable("Gestor");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Avaliacao", b =>
                {
                    b.HasOne("college_management.Dados.Modelos.Aluno", "Aluno")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("college_management.Dados.Modelos.Gestor", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("GestorId");

                    b.HasOne("college_management.Dados.Modelos.Gestor", "Gestor")
                        .WithMany()
                        .HasForeignKey("GestorId1");

                    b.HasOne("college_management.Dados.Modelos.Materia", "Materia")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Gestor");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.CorpoDocente", b =>
                {
                    b.HasOne("college_management.Dados.Modelos.Docente", "Docente")
                        .WithMany("CorpoDocente")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("college_management.Dados.Modelos.Gestor", null)
                        .WithMany("CorposDocentes")
                        .HasForeignKey("GestorId");

                    b.HasOne("college_management.Dados.Modelos.Gestor", "Gestor")
                        .WithMany()
                        .HasForeignKey("GestorId1");

                    b.HasOne("college_management.Dados.Modelos.Materia", "Materia")
                        .WithMany("CorpoDocente")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Gestor");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.GradeCurricular", b =>
                {
                    b.HasOne("college_management.Dados.Modelos.Curso", "Curso")
                        .WithMany("GradesCurriculares")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("college_management.Dados.Modelos.Gestor", null)
                        .WithMany("Grades")
                        .HasForeignKey("GestorId");

                    b.HasOne("college_management.Dados.Modelos.Gestor", "Gestor")
                        .WithMany()
                        .HasForeignKey("GestorId1");

                    b.HasOne("college_management.Dados.Modelos.Materia", "Materia")
                        .WithMany("GradesCurriculares")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Gestor");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Matricula", b =>
                {
                    b.HasOne("college_management.Dados.Modelos.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("college_management.Dados.Modelos.Curso", "Curso")
                        .WithMany("Matriculas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("college_management.Dados.Modelos.Gestor", null)
                        .WithMany("Matriculas")
                        .HasForeignKey("GestorId");

                    b.HasOne("college_management.Dados.Modelos.Gestor", "Gestor")
                        .WithMany()
                        .HasForeignKey("GestorId1");

                    b.Navigation("Aluno");

                    b.Navigation("Curso");

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Modelo", b =>
                {
                    b.HasOne("college_management.Dados.Modelos.Gestor", null)
                        .WithMany("Modelos")
                        .HasForeignKey("GestorId");

                    b.HasOne("college_management.Dados.Modelos.Gestor", "Gestor")
                        .WithMany()
                        .HasForeignKey("GestorId1");

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.TurmaAluno", b =>
                {
                    b.HasOne("college_management.Dados.Modelos.Aluno", "Aluno")
                        .WithMany("TurmaAlunos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("college_management.Dados.Modelos.Gestor", "Gestor")
                        .WithMany()
                        .HasForeignKey("GestorId");

                    b.HasOne("college_management.Dados.Modelos.Turma", "Turma")
                        .WithMany("TurmaAlunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Gestor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Turma", b =>
                {
                    b.HasOne("college_management.Dados.Modelos.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId");

                    b.HasOne("college_management.Dados.Modelos.Docente", null)
                        .WithMany("Turmas")
                        .HasForeignKey("DocenteId1");

                    b.HasOne("college_management.Dados.Modelos.Materia", null)
                        .WithMany("Turmas")
                        .HasForeignKey("MateriaId");

                    b.HasOne("college_management.Dados.Modelos.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId1");

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Curso", b =>
                {
                    b.Navigation("GradesCurriculares");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Materia", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("CorpoDocente");

                    b.Navigation("GradesCurriculares");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Turma", b =>
                {
                    b.Navigation("TurmaAlunos");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Aluno", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Matriculas");

                    b.Navigation("TurmaAlunos");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Docente", b =>
                {
                    b.Navigation("CorpoDocente");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("college_management.Dados.Modelos.Gestor", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("CorposDocentes");

                    b.Navigation("Grades");

                    b.Navigation("Matriculas");

                    b.Navigation("Modelos");
                });
#pragma warning restore 612, 618
        }
    }
}
